# Generated by Django 5.1.3

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(max_length=200)),
                ("index_number", models.CharField(max_length=60, unique=True)),
                ("department", models.CharField(blank=True, max_length=120, null=True)),
                ("level", models.CharField(blank=True, max_length=40, null=True)),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["full_name", "index_number"],
                "indexes": [
                    models.Index(fields=["full_name"], name="students_st_full_na_c4b46f_idx"),
                    models.Index(fields=["index_number"], name="students_st_index_n_0d0158_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("ENTRY", "Entry"), ("EXIT", "Exit")], max_length=5)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="students.student")),
            ],
            options={
                "ordering": ["-timestamp", "-id"],
                "indexes": [
                    models.Index(fields=["student", "timestamp"], name="students_at_student__7ef4db_idx"),
                    models.Index(fields=["action", "timestamp"], name="students_at_action_3c6ff1_idx"),
                ],
            },
        ),
    ]

