# Generated by Django 5.1.3 on 2026-06-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='students_at_student_a692fd_idx',
            old_name='students_at_student__7ef4db_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancerecord',
            new_name='students_at_action_31d883_idx',
            old_name='students_at_action_3c6ff1_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_full_na_6ea9f7_idx',
            old_name='students_st_full_na_c4b46f_idx',
        ),
        migrations.RenameIndex(
            model_name='student',
            new_name='students_st_index_n_cc858e_idx',
            old_name='students_st_index_n_0d0158_idx',
        ),
    ]
