# Generated by Django 5.1.3 on 2025-12-20 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(default='University Library', max_length=200)),
                ('capacity_limit', models.PositiveIntegerField(default=500)),
                ('warning_threshold_percent', models.PositiveIntegerField(default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryExitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('event_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('WEB_MANUAL', 'Web Manual'), ('ADMIN_OVERRIDE', 'Admin Override'), ('RFID', 'RFID')], default='WEB_MANUAL', max_length=20)),
                ('gate', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_time', '-id'],
                'indexes': [models.Index(fields=['event_time'], name='tracking_en_event_t_225446_idx'), models.Index(fields=['user', 'event_time'], name='tracking_en_user_id_7aa399_idx'), models.Index(fields=['event_type', 'event_time'], name='tracking_en_event_t_cf7884_idx')],
            },
        ),
    ]
